# Generated by Django 4.2.10 on 2025-03-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='plante_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userplante',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userplante',
            name='users_plantes_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
